map_frame: map
base_frame: base_link_1
odom_frame: odom_1
slam_gmapping/map_update_interval: 1
maxRange: 5.0
maxUrange: 5.0
sigma: 0.05
kernelSize: 1
lstep: 0.2
astep: 0.1
iterations: 5
lsigma: 0.75
ogain: 3.0
lskip: 0
minimumScore: 100
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 2.0
angularUpdate: 2.0
temporalUpdate: -1
resampleThreshold: 0.5
particles: 50
xmin: -100.0
ymin: -100.0
xmax: 100.0
ymax: 100.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005


